### ISSUE TITLE
[runPython_bot] Message too long error not handled

### ISSUE THREAD

**Issue by aahnik** [aahnik/lovely-telegram#3]
```
2020-10-31 12:06:50,149 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.                                    
Traceback (most recent call last):                                                                                                                  
  File "/home/aahnik/projects/lovely-telegram/runPython_bot/venv/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 425, in process_updat
e                                                                                                                                                   
    handler.handle_update(update, self, check, context)                                                                                             
  File "/home/aahnik/projects/lovely-telegram/runPython_bot/venv/lib/python3.8/site-packages/telegram/ext/handler.py", line 145, in handle_update   
    return self.callback(update, context)                                                                                                           
  File "/home/aahnik/projects/lovely-telegram/runPython_bot/bot/runPython_bot.py", line 42, in reply                                                
    context.bot.send_message(                                                                                                                       
  File "<decorator-gen-2>", line 2, in send_message                                                                                                 
  File "/home/aahnik/projects/lovely-telegram/runPython_bot/venv/lib/python3.8/site-packages/telegram/bot.py", line 78, in decorator                
    result = func(*args, **kwargs)                                                                                                                  
  File "/home/aahnik/projects/lovely-telegram/runPython_bot/venv/lib/python3.8/site-packages/telegram/bot.py", line 382, in send_message            
    return self._message('sendMessage', data,  # type: ignore[return-value]                                                                         
  File "/home/aahnik/projects/lovely-telegram/runPython_bot/venv/lib/python3.8/site-packages/telegram/bot.py", line 215, in _message                
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)                                                                     
  File "/home/aahnik/projects/lovely-telegram/runPython_bot/venv/lib/python3.8/site-packages/telegram/bot.py", line 184, in _post                   
    return self.request.post('{}/{}'.format(self.base_url, endpoint), data=data,                                                                    
  File "/home/aahnik/projects/lovely-telegram/runPython_bot/venv/lib/python3.8/site-packages/telegram/utils/request.py", line 325, in post          
    result = self._request_wrapper('POST', url,                                                                                                     
  File "/home/aahnik/projects/lovely-telegram/runPython_bot/venv/lib/python3.8/site-packages/telegram/utils/request.py", line 250, in _request_wrapp
er                                                                                                                                                  
    raise BadRequest(message)                                                                                                                       
telegram.error.BadRequest: Message is too long       
```

**Comment by aahnik** [comment]
constants.MAX_MESSAGE_LENGTH
python-telegram-bot documentation for this attribute:
[telegram.constants.MAX_MESSAGE_LENGTH](https://python-telegram-bot.readthedocs.io/en/stable/telegram.constants.html#telegram.constants.MAX_MESSAGE_LENGTH)

**Comment by aahnik** [comment]
message output limited to 2000 characters

**Comment by aahnik** [comment]
![image](https://user-images.githubusercontent.com/66209958/97782505-d9aeaa80-1bb7-11eb-8983-5d88da0763de.png)
